sudo: required
language: node_js
node_js:
  - "8"
  - "10"
  - "12"

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Audit
      script: npm audit --production
    - stage: Npm release
      node_js: "8"
      script:
        - echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        on:
          tags: true

    - stage: Github release
      before_install:
        - npm install -g nexe
      script:
        - nexe -i tomoxjs -t linux-x64 -o tomoxjs.$TRAVIS_TAG.linux-x64 -r ./
        - nexe -i tomoxjs -t darwin-x64 -o tomoxjs.$TRAVIS_TAG.darwin-x64 -r ./
        - nexe -i tomoxjs -t windows-x64 -o tomoxjs.$TRAVIS_TAG.windows-x64.exe -r ./
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        overwrite: true
        file:
          - tomoxjs.$TRAVIS_TAG.linux-x64
          - tomoxjs.$TRAVIS_TAG.windows-x64.exe
          - tomoxjs.$TRAVIS_TAG.darwin-x64
        on:
          tags: true

stages:
  - name: Lint
  - name: Audit
  - name: Test
  - name: Npm release
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = tomochain/tomoxjs
  - name: Github release
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = tomochain/tomoxjs
